spring:
  datasource:
    url: jdbc:mysql://192.168.1.230:3306/gdcc315?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: root
    password: Ccr@1688
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource

  #redis配置
  redis:
    host: 192.168.1.202
    password: 123456
    port: 6379
    timeout: 50000
    database: 13
    lettuce:
      pool:
        max-active: 12 # 大于cpu*2
        max-idle: 12 # cpu*2
        max-wait: 5s
        time-between-eviction-runs: 1s

#配置日志
logging:
  level:
    net.mingsoft: debug
  config: classpath:log4j-spring.xml

saveAttachmentPath: d://