# 广东消委会生产配置
spring:
  datasource:
    url: jdbc:mysql://192.168.0.101:3306/gdcc315?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: gdccadmin
    password: Ccr@1688
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource

#配置日志
logging:
  level:
    net.mingsoft: info
  config: classpath:log4j-spring.xml